# netlify configuration
# https://docs.netlify.com/build/configure-builds/file-based-configuration/
[build]
  command = "pipenv run python ./site build && pipenv run python -m pagefind --site build"
  publish = "build"

