---

- name: Configure Agoric Node
  hosts: colos
  become: yes
  vars_files:
    - ../priv/vault1.yml
  vars:
    config_dir: /var/lib/docker/volumes/ag-chain-cosmos-state/_data/config
    moniker: dckc
  tasks:
    - name: get network config
      uri:
        url: https://devnet.agoric.net/network-config
        method: GET
        return_content: yes
        status_code: 200
      register: network_config
    - debug: var=(network_config.content|from_json).chainName
    - debug: var=(network_config.content|from_json).peers
    - debug: var=(network_config.content|from_json).seeds
    - name: ensure genesis.json is out of the way
      file: path={{ config_dir }}/genesis.json state=absent
    - name: init
      command: |
        docker run --rm \
        -v ag-chain-cosmos-state:/root/.ag-chain-cosmos \
        --entrypoint=/usr/local/bin/ag-chain-cosmos \
        agoric/agoric-sdk:{{ ag_sdk_tag }} \
        init --chain-id "{{ (network_config.content|from_json).chainName }}" "{{ moniker }}"
    - name: Download genesis file
      get_url:
        url: https://devnet.agoric.net/genesis.json
        force: true
        dest: "{{ config_dir }}/genesis.json"
    - name: Set peers variable to the correct value
      lineinfile:
        path: "{{ config_dir }}/config.toml"
        regexp: "^persistent_peers *="
        line: "persistent_peers = \"{{ (network_config.content|from_json).peers|join(',') }}\""
    - name: Set seeds
      lineinfile:
        path: "{{ config_dir }}/config.toml"
        regexp: "^seeds *="
        line: "seeds = \"{{ (network_config.content|from_json).seeds|join(',') }}\""
